# This dockerfile uses haproxy image
# VERSION 1.0
# Author: zhaojianhui
# Command format: Instruction [arguments / command] ..

FROM elasticsearch:5.5.0

# 更新类库
RUN apt-get update && apt-get upgrade -y